---
version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@volatile

jobs:
  debian_build:
    executor: greenzie/debian_builder
    steps:
      - checkout
      - run:
          name: Build and Publish Debian Package
          command: |
            bash .circleci/build_debian_package.sh
            

workflows:
  version: 2
  pushbuild:
    unless: << pipeline.parameters.manual-bobcat-deploy >>
    jobs:
      # Build jobs
      - debian_build:
          context: GREENZIE

