---
version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@volatile

parameters:
  manual_deploy:
    type: boolean
    default: false

commands:
  build_debian_packages:
    steps:
      - checkout
      - run:
          name: Build and Publish Debian Package
          command: |
            pwd
            cd $CIRCLE_WORKING_DIRECTORY
            bash .circleci/build_debian_packages.sh
            cd /root/
            tar -cvf /debians/alldebians.tar -C /debians/ .
      - store_artifacts:
          path: /debians/
          destination: debian_packages
      - persist_to_workspace:
          root: /debians/
          paths:
            - '*'

jobs:
  debian_build:
    executor: greenzie/debianize_amd64
    steps:
      - build_debian_packages
  debian_build_arm64:
    executor: greenzie/debianize_arm64
    steps:
      - run:
          name: Fix arm64 sources
          command: |
                set -x
                server=http://aptly.greenzie.com
                UBUNTU_DISTRO=focal
                rm -r /etc/apt/sources.list.d/*
                ls -lah /etc/apt/
                cat /etc/apt/sources.list
                echo "deb ${server}/greenzie-experimental ${UBUNTU_DISTRO} main" > /etc/apt/sources.list
                echo "deb ${server}/ubuntu-arm64-experimental ${UBUNTU_DISTRO} main" >> /etc/apt/sources.list

                # The base image has a newer version of libuuid1 than what something in this chain of dependencies needs:
                # ros-noetic-roscpp ros-noetic-rosconsole ros-noetic-rosbag ros-noetic-topic-tools libapr1-dev libaprutil1-dev liblog4cxx-dev uuid-dev
                # downgrades are not done automatically, so we have to do it manually here.
                # This avoids apt -y build-dep . failures.
                apt-get update
                apt-get install -y --allow-downgrades libuuid1=2.34-0.1ubuntu9.4

      - build_debian_packages


workflows:
  version: 2
  pushbuild:
    when: not << pipeline.parameters.manual_deploy>>
    jobs:
      # Build jobs
      - debian_build:
          context: GREENZIE
      - debian_build_arm64:
          context: GREENZIE

  manual_deploy:
    when: << pipeline.parameters.manual_deploy>>
    jobs:
      - debian_build:
          context: GREENZIE
      - debian_build_arm64:
          context: GREENZIE
      - greenzie/debian_deploy_experimental:
          name: "deploy_amd64_greenzie"
          context: GREENZIE
          requires:
            - debian_build
            - debian_build_arm64
