---
version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@volatile

parameters:
  manual_deploy:
    type: boolean
    default: false

jobs:
  debian_build:
    executor: greenzie/debianize_amd64
    steps:
      - checkout
      - run:
          name: Build and Publish Debian Package
          command: |
            pwd
            cd $CIRCLE_WORKING_DIRECTORY
            bash .circleci/build_debian_packages.sh
            cd /root/
            tar -cvf /debians/alldebians.tar -C /debians/ .
      - store_artifacts:
          path: /debians/
          destination: debian_packages
      - persist_to_workspace:
          root: /debians/
          paths:
            - '*'

workflows:
  version: 2
  pushbuild:
    when: not << pipeline.parameters.manual_deploy>>
    jobs:
      # Build jobs
      - debian_build:
          context: GREENZIE

  manual_deploy:
    when: << pipeline.parameters.manual_deploy>>
    jobs:
      - debian_build:
          context: GREENZIE
      - greenzie/debian_deploy_experimental:
          name: "deploy_amd64_greenzie"
          context: GREENZIE
          requires:
            - debian_build
