version: 2.1

workflows:
  version: 2
  pushbuild:
    jobs:
      - debian_build:
          name: "amd_debian_build"
          resource_class: 'small'
          platform: amd64

      - debian_build:
          name: "arm_debian_build"
          resource_class: 'arm.medium'
          platform: arm64

      - deploy:
          name: "deploy amd64 to greenzie.com"
          filters:
            branches:
              only:
                - noetic
          requires:
            - amd_debian_build
      - deploy:
          name: "deploy arm64 to greenzie.com"
          filters:
            branches:
              only:
                - noetic
          requires:
            - arm_debian_build
      - deploy:
          name: "deploy to bobcat.greenzie.com"
          server_hostname: bobcat-aptly.greenzie.com
          filters:
            branches:
              only:
                - noetic
          requires:
            - arm_debian_build
            - amd_debian_build

executors:
  docker_arm64:
    docker:
      - image: greenzie/ci-debianize:focal-noetic
        auth:
          username: $DOCKERHUB_GREENZIE_USERNAME
          password: $DOCKERHUB_GREENZIE_PASSWORD
    resource_class: arm.medium

  docker_amd64:
    docker:
      - image: greenzie/ci-debianize:focal-noetic
        auth:
          username: $DOCKERHUB_GREENZIE_USERNAME
          password: $DOCKERHUB_GREENZIE_PASSWORD
    resource_class: small

jobs:
  debian_build:
    executor: docker_<< parameters.platform >>
    parameters:
      resource_class:
        type: string
        default: small
      platform:
        type: string
        default: amd64
    steps:
      - checkout
      - run:
          name: "Generate Changelogs"
          command: greenzie-release changelog -r "${ROS_DISTRO}"
      - run:
          name: "Package debs (debuild)"
          environment:
            - TARGETPLATFORM: << parameters.platform >>
          command: GITHUB_WORKSPACE="$PWD" greenzie-debianize all
      - store_artifacts:
          path: /debians
      - persist_to_workspace:
          root: /debians
          paths:
            - '*'

  deploy:
    docker:
      - image: greenzie/aptly:3.19.1-focal-noetic
        auth:
          username: $DOCKERHUB_GREENZIE_USERNAME
          password: $DOCKERHUB_GREENZIE_PASSWORD
    resource_class: small
    parameters:
      server_hostname:
        type: string
        default: aptly.greenzie.com
      architecture:
        type: string
        default: ""
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: /debians
      - run:
          name: Deploy to << parameters.server_hostname >>
          environment:
            SERVER_HOSTNAME: << parameters.server_hostname >>
            ARCHITECTURE: << parameters.architecture >>
          command: |
            ls-lah /debians/
            if [ -z "${ARCHITECTURE}" ]; then
              echo "No architecture specified, deploying all"
              greenzie-aptly repo deploy -r experimental -n "${CIRCLE_BUILD_NUM}" -p "/debians"
            else
              greenzie-aptly repo deploy -a "${ARCHITECTURE}" -r experimental -n "${CIRCLE_BUILD_NUM}" -p "/debians"
            fi
